[build]
  base    = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/api/*"
  to     = "https://yjm.onrender.com/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/admin/api/*"
  to     = "https://yjm.onrender.com/admin/api/:splat"
  status = 200
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
